In [5]:
import sqlite3
import pandas as pd

engine = sqlite3.connect("sucursal_norte.db")
df_sqlite = pd.read_sql_query("SELECT * FROM clientes", engine)
df_sqlite

   id_cliente    nombre_cliente ciudad_cliente
0        C001     Muebles La 70       Medellin
1        C002       Hogar Bello          Bello
2        C003   Disenos Oriente       Rionegro
3        C003  Disenos Oriente        Rionegro
4        C004        Casa Nogal       Sabaneta
5        C005   Decor Antioquia       Envigado
6        C006  Almacen Laureles       Medellin
7        C007       Roble Hogar         Itagui
8        C008   Espacios Unicos     Copacabana
9        C009       Veta Studio       Medellin
10       C010       Madera Viva          Bello
11       C011  Proyecto Habitat       Envigado
12       C012    Innova Muebles       Rionegro
13       C013      Casa Central       Medellin
14       C014        Nogal Deco       Sabaneta

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("duckdb:///sucursal_norte.duckdb")
df_duckdb = pd.read_sql_query("SELECT * FROM clientes", engine)
df_duckdb

   id_cliente    nombre_cliente ciudad_cliente
0        C001     Muebles La 70       Medellin
1        C002       Hogar Bello          Bello
2        C003   Disenos Oriente       Rionegro
3        C003  Disenos Oriente        Rionegro
4        C004        Casa Nogal       Sabaneta
5        C005   Decor Antioquia       Envigado
6        C006  Almacen Laureles       Medellin
7        C007       Roble Hogar         Itagui
8        C008   Espacios Unicos     Copacabana
9        C009       Veta Studio       Medellin
10       C010       Madera Viva          Bello
11       C011  Proyecto Habitat       Envigado
12       C012    Innova Muebles       Rionegro
13       C013      Casa Central       Medellin
14       C014        Nogal Deco       Sabaneta